#!/bin/bash
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

print(){
  local str="$1"
  echo -e "${GREEN}${str}${NC}"
}

failed(){
  local str="$1"
  echo -e "${RED}${str}${NC}"
}

print "updating & upgrading the system..."
sudo apt-get update 1> /dev/null
sudo apt-get upgrade -y 1> /dev/null


if [ $? -ne 0 ]; then
  failed "failed to upgrade the system"
  exit
fi


print "installing tools..."
sudo apt-get install git curl unzip tar wget fontconfig apt-utils software-properties-common net-tools vim nano zsh -y 1> /dev/null


print "installing the Hack Nerd Font"
curl -fLo "Hack.zip" https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Hack.zip 1> /dev/null

if [ $? -ne 0 ]; then
  failed "failed to install the font"
  exit
fi

mkdir -p ~/.local/share/fonts
unzip Hack.zip -d ~/.local/share/fonts

fc-cache -fv

print "installing the node.js"
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash - 1> /dev/null
sudo apt-get install -y nodejs 1> /dev/null


if [[ $? -ne 0 ]]; then
  failed "failed to install node.js"
  exit
fi

node -v
npm -v


# Neovim
print "installing Neovim"
curl -LO https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-linux64.tar.gz 1> /dev/null

if [[ $? -ne 0 ]]; then
  failed "failed to install neovim"
  exit
fi

NVIM="nvim-linux64.tar.gz"
print "copying files to your system"
tar -xvf ./$NVIM 1> /dev/null

if [[ $? -ne 0 ]]; then
  failed "extracting failed"
  exit
fi

sudo cp -r nvim-linux64/bin/* /usr/bin/.
sudo cp -r nvim-linux64/lib/* /lib/.
sudo cp -r nvim-linux64/share/* /usr/share/.

print "neovim setup done!"

nvim --version


print "copied the .zshrc to you current user home dir"
cp ./zsh/.zshrc ~/.zshrc
