#!/bin/bash
echo "updating & upgrading the system..."
sudo apt-get update 1> /dev/null
sudo apt-get upgrade -y 1> /dev/null


if [ $? -ne 0 ]; then
  echo "failed to upgrade the system"
  exit
fi


echo "installing tools..."
sudo apt-get install git curl unzip tar wget fontconfig net-tools vim nano zsh -y 1> /dev/null


echo "installing the Hack Nerd Font"
curl -fLo "Hack.zip" https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Hack.zip 1> /dev/null

if [ $? -ne 0 ]; then
  echo "failed to install the font"
  exit
fi

mkdir -p ~/.local/share/fonts
unzip Hack.zip -d ~/.local/share/fonts

fc-cache -fv

echo "installing the node.js"
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash - 1> /dev/null
sudo apt-get install -y nodejs 1> /dev/null


if [[ $? -ne 0 ]]; then
  echo "failed to install node.js"
  exit
fi

node -v
npm -v


# Neovim
echo "installing Neovim"
curl -LO https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-linux64.tar.gz 1> /dev/null

if [[ $? -ne 0 ]]; then
  echo "failed to install neovim"
  exit
fi

NVIM="nvim-linux64.tar.gz"
echo "copying files to your system"
tar -xvf ./$NVIM 1> /dev/null

if [[ $? -ne 0 ]]; then
  echo "extracting failed"
  exit
fi

sudo cp -r nvim-linux64/bin/* /usr/bin/.
sudo cp -r nvim-linux64/lib/* /lib/.
sudo cp -r nvim-linux64/share/* /usr/share/.

echo "neovim setup done!"

nvim --version


echo "copied the .zshrc to you current user home dir"
cp ./zsh/.zshrc ~/.zshrc
